############################
## CHANGE THESE
############################


title: "sypth.xyz"

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'
enableRobotsTXT: true